name: Repo SemVer check
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0 # needed to get all tags
      
      - uses: jessehouwing/actions-semver-checker@1a13fd188ebef96fb179faedfabcc8de5cb6189d # v1
